Fix adjustMergeCells not modifies cell rect
qax-os/excelize pull request #1118
Opened 2022-01-11 08:36 UTC by Dokiys

Fix DuplicateRowTo unvalied thad duplicates later row to forehead

# PR Details

Fix adjustMergeCells not modifies cell rect and DuplicateRowTo unvalied thad duplicates later row to forehead

## Description

`MergeCell` after `DupliacteRowTo` will get unexpected result. Such as below cases: 
```go
         // Test merge cell after duplicate null row
	{
		f := excelize.NewFile()
		sheet := "Sheet1"
		assert.NoError(t, f.MergeCell(sheet,"A4","A5"))

		assert.NoError(t, f.DuplicateRowTo(sheet, 2, 3))
		assert.NoError(t, f.DuplicateRowTo(sheet, 2, 4))
		assert.NoError(t, f.MergeCell(sheet,"A2","A3"))
		assert.NoError(t, f.MergeCell(sheet,"A3","A4"))

		mergeCells, err := f.GetMergeCells(sheet)
		assert.NoError(t, err)
		assert.ElementsMatch(t, mergeCells, []excelize.MergeCell{{"A6:A7",""},{"A2:A4",""}})
	}

	// Test merge cell after duplicate null col
	{

		f := excelize.NewFile()
		sheet := "Sheet1"

		assert.NoError(t, f.MergeCell(sheet,"D1","E1"))

		assert.NoError(t, f.InsertCol(sheet, "C"))
		assert.NoError(t, f.InsertCol(sheet, "D"))
		assert.NoError(t, f.MergeCell(sheet,"B1","C1"))
		assert.NoError(t, f.MergeCell(sheet,"C1","D1"))

		mergeCells, err := f.GetMergeCells(sheet)
		assert.NoError(t, err)
		assert.ElementsMatch(t, mergeCells, []excelize.MergeCell{{"B1:D1",""},{"F1:G1",""}})
	}
```
Related unit test have been added in test file.

## Related Issue

## Motivation and Context

## How Has This Been Tested

Run unit testing.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

2022-01-13 05:25 UTC, xuri requested changes
Thanks for your PR, I've left some comments. Please follows the code style of this project, and lint the code with `go fmt -s`.

2022-01-13 05:25 UTC, xuri commented on rows.go
>  		return nil
Could you add unit test for this exception case?

2022-01-13 05:25 UTC, xuri commented on rows.go
>  		return err
The unit test doesn't cover this case currently, please add the test for this.

2022-01-13 16:28 UTC, xuri approved these changes

2022-01-13 16:28 UTC, merged

2022-01-13 16:30 UTC, xuri commented
I made some changes based on your branch.

2022-01-15 12:43 UTC, Dokiys commented
> I made some changes based on your branch.

OK. Thanks.