Initialize GetDataValidation and GetConditionalFormat for sheets
qax-os/excelize pull request #1315
Opened 2022-08-12 14:13 UTC by chenliu1993

Signed-off-by: chenliu1993 <13630583107@163.com>

# PR Details

## Description
This PR adds functions for getting data validations and conditional format strings across all sheets initially. 
This should fix initially for #827 

## Related Issue
#827 

## Motivation and Context
Just complete the function for these two fields

## How Has This Been Tested
Simply add two unit tests for these two functions

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-25 07:22 UTC, xuri requested changes
Thanks for your contribution. I've left some comments.

2022-08-25 07:22 UTC, xuri commented on datavalidation.go
> +			dv := *item
The variable `item` is a pointer of the data validation, this code can be simplified by appending it to the result map directly.

2022-08-25 07:22 UTC, xuri commented on styles.go
> +				cfRuleBytes, err := xml.Marshal(cfRule)
The result of this function should be same with the parameter `formatSet` of the `SetConditionalFormat` function. In another word, that the serilized string of `formatConditional`. So I think the new exported data type `CfRule` is not required.

2022-08-26 16:41 UTC, xuri approved these changes

2022-08-26 16:45 UTC, merged

2022-08-29 03:42 UTC, chenliu1993 commented
Sorry for the late notice......