feat: DelComment
qax-os/excelize pull request #1317
Opened 2022-08-14 18:29 UTC by NaturalGao

new DelComment function

# PR Details

## Description

增加删除批注功能函数 DelComment [#849 ]

## Motivation and Context

最近项目有用到这个库，挺棒的一个库！刚好在社群又看到有这么个需求，于是尝试贡献下自己的代码。

## How Has This Been Tested

添加了一个单元测试函数

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-08-15 07:30 UTC, xuri requested changes
Thanks for your PR. I've left some comments.

2022-08-15 07:30 UTC, xuri commented on comment.go
> +	sheetFile, sheetExist := f.sheetMap[sheet]
Use the `workSheetReader` to check the worksheet if exists, and you will also get the pointer of the deserialized worksheet structure. This pull request won't remove the `legacyDrawing` of the worksheet when all comments on the worksheet have been removing. I think we need to remove it, so receive the pointer of the deserialized worksheet structure here to do that, and you needn't create a new error for not exist worksheet. Note that the exported errors should be defined in the `errors.go`.

2022-08-15 07:30 UTC, xuri commented on comment.go
> +		err = errors.New("comment target is null")
This internal error can be skipped, remove the errors return.

2022-08-15 07:30 UTC, xuri commented on comment.go
> +					comments.CommentList.Comment = []xlsxComment{}
The worksheet relationships and the `legacyDrawing` of the worksheet also should be removed, if all comments on the worksheet have been removed.

2022-08-15 07:30 UTC, xuri commented on comment.go
> +				} else {
In my personal approach of choosing one is that using continue statement instead of else.

2022-08-15 07:30 UTC, xuri commented on comment_test.go
> +func TestDelComments(t *testing.T) {
Rename `TestDelComments` to `TestDeleteComment`.

2022-08-19 15:00 UTC, xuri approved these changes
I made some changes based on your branch.

2022-08-19 15:07 UTC, NaturalGao commented
happy weekend! Thank you for your help! @xuri

2022-08-19 15:24 UTC, merged