feat: Add a GetPicutreCells function
qax-os/excelize pull request #1634
Opened 2023-08-28 01:29 UTC by yicixin

# PR Details

## Description
When I import an xlsx, I need to go through all the cells to get the pictures,  each call to the getPicture function traverses all the pictures, why not just provide a way to get all the pictures at once.

## Related Issue

## Motivation and Context

## How Has This Been Tested

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-08-30 20:09 UTC, sides-flow commented
I could really use this functionality as well!
I hope it gets merged soon, thanks!

2023-09-08 09:04 UTC, yicixin commented
When will this commit can be merged? 🤣

2023-09-08 09:37 UTC, xuri commented
Thanks for your pull request. I need some time to review.

2023-10-12 02:05 UTC, xuri requested changes
Sorry for the late reply. I've left some comments.

2023-10-12 02:05 UTC, xuri commented on picture.go
> +func (f *File) GetAllPictures(sheet string) (map[string][]Picture, error) {
Every exported function should have unit tests and the line coverage should approach 100%.

2023-10-12 16:05 UTC, xuri approved these changes
LGTM. Thanks for your contribution. I have made some changes based on your branch. This feature will be released in the next version.

2023-10-12 16:06 UTC, merged